name: Vault Radar Scan (via Container)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vault-radar:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔄 Pull image
        run: docker pull repping/vault_radar_container.slim:0.0.2 || true

      - name: 🛡️ Run Vault Radar inside container
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
        run: |
          docker run --rm \
            --platform linux/amd64 \
            --env HCP_CLIENT_ID \
            --env HCP_CLIENT_SECRET \
            --env HCP_PROJECT_ID \
            -v "$PWD":/data \
            -w /data \
            repping/vault-radar-cli \
            scan folder \
            --path . \
            --disable-ui \
            --outfile scan_file.csv \
            --format csv

          EXIT_CODE=$?

          if [[ -f scan_file.csv ]]; then
            echo "✅ scan_file generated"
            echo ""
            echo "🔍 Vault Radar Findings:"
            echo "------------------------"
            cat scan_file.csv
            echo "------------------------"
          else
            echo "❌ scan_file NOT generated"
            ls -lh
          fi

          mkdir -p findings
          mv scan_file.csv findings/ || true

          # 🔎 Low severity warning (non-blocking)
          if grep -iqE ',low,' findings/scan_file.csv; then
            echo "::warning file=findings/scan_file.csv,title=Low severity detected::ℹ️ Vault Radar found low severity issues"
            echo "ℹ️ Low severity findings detected" >> $GITHUB_STEP_SUMMARY
          fi
          
          # 🔎 Medium severity warning (non-blocking)
          if grep -iqE ',medium,' findings/scan_file.csv; then
            echo "::warning file=findings/scan_file.csv,title=Medium severity detected::⚠️ Vault Radar found medium severity issues"
            echo "⚠️ Medium severity findings detected" >> $GITHUB_STEP_SUMMARY
          fi

          # ❌ High/Critical severity = block
          if grep -iqE ',(high|critical),' findings/scan_file.csv; then
            echo "::error file=findings/scan_file.csv,title=High or Critical severity::❌ Vault Radar found HIGH or CRITICAL severity issues"
            echo "❌ **High or critical severity findings detected. Blocking the build.**" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "✅ No high or critical findings detected" >> $GITHUB_STEP_SUMMARY
          fi

          echo "📝 Scan results saved to findings/scan_file.csv" >> $GITHUB_STEP_SUMMARY
          exit $EXIT_CODE

      - name: 📦 Archive scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: radar-scan-results
          path: findings/scan_file.csv
